### ISSUE TITLE
Layout of media page needs improvement

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#12]
**Sender**: mark@crashoverride.com
**Taken at**: http://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/media
**Fields**:
- Add a comment: The size and layout of this page just seems off. What is built is by design but the text in the highlighted box is not legible.

![SCREENSHOT](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/be09f32d-ba60-44d6-9390-f2a18bfef6e1-annotated_d19dac26-8b17-40fb-a07c-142d4b2a0c3c.png?etag=a78e2c3ef7f4f2e582c0646c21ffff12)
*[Download original image](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/be09f32d-ba60-44d6-9390-f2a18bfef6e1-annotated_d19dac26-8b17-40fb-a07c-142d4b2a0c3c.png?etag=a78e2c3ef7f4f2e582c0646c21ffff12)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 3840x1600
**Browser size**: 2109x1202
**[Open #9 in Usersnap](https://app.usersnap.com/l/feedback/d364b931-b550-4adc-af7d-17639b2d3ae3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by alexdunphy** [comment]
The [Media](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/media) page content shouldn't overlap now like in the flagged screenshot above - but I'll leave this issue open for the moment until the Symbols section has been added to the page.

**Comment by alexdunphy** [comment]
@curphey The Symbols section has been added to the page - the attachment file can be [uploaded here](https://app-eu1.hubspot.com/content/25939634/staging/domain/49440753384/manage/stagedProof), under Content > Symbols:

![CleanShot 2022-09-26 at 10 11 15@2x](https://user-images.githubusercontent.com/1374671/192240309-4e69e076-2411-44a4-a478-6a52248d39a3.png)

I don't think I have the permissions to publish these changes to the site, but there's a preview of the page with the section added here: https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/media?hs_preview=bJwZZetx-52548674498
