### ISSUE TITLE
Nav Bar Text Not Legible 

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#13]
White text on the neon green background has no contast

![Screenshot 2022-09-04 at 16 07 53](https://user-images.githubusercontent.com/143776/188320409-f7e302b9-2d4a-4d82-8cad-82e250bfab25.png)

**Comment by alexdunphy** [comment]
This should be fixed now: https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/contact.
