### ISSUE TITLE
Indentation is privacy page not correct

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#15]
**Sender**: mark@crashoverride.com
**Taken at**: https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/privacy
**Fields**:
- Add a comment: Indentation is not correct

![SCREENSHOT](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/d33f7914-04a7-42cd-99b0-62002eac6c7a-annotated_0ff3262a-2eef-4284-bdb3-075011aac476.png?etag=d57d98db23aa5504de9ccacccbf7e682)
*[Download original image](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/d33f7914-04a7-42cd-99b0-62002eac6c7a-annotated_0ff3262a-2eef-4284-bdb3-075011aac476.png?etag=d57d98db23aa5504de9ccacccbf7e682)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 3840x1600
**Browser size**: 2109x1202
**[Open #11 in Usersnap](https://app.usersnap.com/l/feedback/d16f60e7-634d-42a5-88a3-8b42c100073e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by alexdunphy** [comment]
@curphey This has been fixed on the Privacy page - there's a [page preview here](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/privacy?hs_preview=iBgGZsrd-52544255705), in case you get a chance to publish this in the [admin here](https://app-eu1.hubspot.com/content/25939634/edit/52544255705/content).

Here's a screenshot of the indentation in the design mockup:

<img width="1368" alt="CleanShot 2022-09-26 at 10 30 58@2x" src="https://user-images.githubusercontent.com/1374671/192243040-e63abda4-703e-4878-ba41-dcf2b84e5e57.png">
