### ISSUE TITLE
Missing Grid Edges

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#17]
**Sender**: mark@crashoverride.com
**Taken at**: http://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/thank-you
**Fields**:
- Add a comment: Missing Grid Edges

![SCREENSHOT](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/974abb26-fd41-4560-b2a6-659c632dc764-annotated_7fbdc826-42ce-408c-8a33-c67e49981ba7.png?etag=f11117c9a82af73ff026d9875de9fbee)
*[Download original image](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/974abb26-fd41-4560-b2a6-659c632dc764-annotated_7fbdc826-42ce-408c-8a33-c67e49981ba7.png?etag=f11117c9a82af73ff026d9875de9fbee)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 3840x1600
**Browser size**: 2109x1202
**[Open #13 in Usersnap](https://app.usersnap.com/l/feedback/e2a103e4-66ee-45de-8fc4-536b3a7f9bd1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by curphey** [comment]
From @alexdunphy think it’d be best to make this a repeating pattern rather than a fixed-size image, so it can scale better with the content and resize down a bit better on mobile. This change would apply to other pages too, e.g. the large grid behind the page content on the About page.)

Makes total sense. 

Mailto links don’t work: (Are you still seeing this issue? I’ve tried one of the links on this page and it works OK, so just want to check before we have a look at it. It looks like Hubspot protects mailto links by default and requires JS for them to work, so if e.g. JS is disabled then you would see ‘Email protected’ rather than the email - in case there’s a side-effect of this that’s causing the mailto link not to work for you.)

Works now. Lets close that part of this for now.

**Comment by alexdunphy** [comment]
Thanks for adding the comments from Basecamp here.

The grid has been switched to a CSS pattern, and should line up better on the [Thanks](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/thank-you) and [404](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/404) pages.

The same pattern is used for the main content area on the [About](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/about) page, so the grid lines should line up a bit more neatly with the content boxes there too now.
