### ISSUE TITLE
Title text style on Privacy Page not as per design

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#18]
**Sender**: mark@crashoverride.com
**Taken at**: https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/privacy
**Fields**:
- Add a comment: Title text style not as per design

![SCREENSHOT](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/8c1cf8d8-3f84-473b-85b5-96ba15d31997-annotated_09aaf8b8-8927-459f-8833-9f126f66edc8.png?etag=b9fcc115e5f3b066c43cadadd6c0f52e)
*[Download original image](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/8c1cf8d8-3f84-473b-85b5-96ba15d31997-annotated_09aaf8b8-8927-459f-8833-9f126f66edc8.png?etag=b9fcc115e5f3b066c43cadadd6c0f52e)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 3840x1600
**Browser size**: 2109x1202
**[Open #14 in Usersnap](https://app.usersnap.com/l/feedback/0ba35ed6-5810-46f1-b93a-ae77204acc4f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by alexdunphy** [comment]
@curphey This has been fixed on the Privacy page - there's a [page preview here](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/privacy?hs_preview=iBgGZsrd-52544255705), in case you get a chance to publish this in the [admin here](https://app-eu1.hubspot.com/content/25939634/edit/52544255705/content).
