### ISSUE TITLE
Safari: Buttons don't render correctly

### ISSUE THREAD

**Issue by viega** [crashappsec/www-qa-issues#19]
Submit button on home page.

<img width="1354" alt="Screen Shot 2022-09-04 at 11 39 41 AM" src="https://user-images.githubusercontent.com/4764481/188321991-343bdde7-4e28-46ee-bc13-3b4fed4e88f2.png">

**Comment by alexdunphy** [comment]
The button text wrapping should be fixed here in Safari now.
