### ISSUE TITLE
Reduce cookie banner size

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#2]
**Sender**: mark@crashoverride.com
**Taken at**: https://crashoverride-25939634.hs-sites-eu1.com/
**Fields**:
- Add a comment: Can we make this smaller ? I have looked at other Hubspot sites and its not this large. 

![SCREENSHOT](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/9c2b6e94-6d52-44ce-a14e-9d392166004e-annotated_2821ebed-2633-4592-961a-e5b146ab0054.png?etag=3312a703a40b728eb88fa20079db1bac)
*[Download original image](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/9c2b6e94-6d52-44ce-a14e-9d392166004e-annotated_2821ebed-2633-4592-961a-e5b146ab0054.png?etag=3312a703a40b728eb88fa20079db1bac)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 1800x1169
**Browser size**: 1591x859
**[Open #5 in Usersnap](https://app.usersnap.com/l/feedback/6abf3350-aae9-4f68-88b2-535b841a9d80?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by alexdunphy** [comment]
The cookie banner is more compact now, and the styling has been updated to fit better with the site theme. The font-size could still be reduced a little more if needed.

![Cookie-Banner](https://user-images.githubusercontent.com/1374671/192039870-1c5ce542-170b-45dc-85c0-86950fc46541.png)
