### ISSUE TITLE
Safari: Nothing in the menu works

### ISSUE THREAD

**Issue by viega** [crashappsec/www-qa-issues#20]
The menu items, when clicked do nothing on Safari.  Hovering over 'Resources' does load the sub-menu, but nothing works when clicked.  Clicking the logo DOES seem to reload the page.

**Comment by viega** [comment]
BTW, using Safari 15.6 on a M1 MacBook Pro

**Comment by nettrino** [comment]
I am seeing the same in chrome but I simply thought functionality is still pending there

**Comment by alexdunphy** [comment]
The menu links have been updated based on the call this afternoon. Now the dropdown nav has 'Articles' which links to the [Blog](https://blog.crashoverride.com/blog), and 'Media Kit' which links to the [Media](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/media) page.

The menu links [are editable here](https://app-eu1.hubspot.com/menus/25939634/edit/), so the Open Source item in the Resources dropdown can be restored when that's ready to go.
