### ISSUE TITLE
Media page founders' media links have wrong attachments and are mis-aligned

### ISSUE THREAD

**Issue by nettrino** [crashappsec/www-qa-issues#21]
The dark/white media logos are downloaded when clicking on the bio zip files. The bundled link downloads an html page. Finally, the alignments of the photos and links are off as seen from the screenshot below

<img width="1250" alt="Screenshot 2022-09-05 at 12 16 16 AM" src="https://user-images.githubusercontent.com/4614044/188333886-9f07f034-899f-4cec-8c97-6d37a1b4f456.png">

**Comment by alexdunphy** [comment]
The alignment should be fixed here on the [Media](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/media) page now, but I'll leave this issue open for the moment until the attachments are added next week.

**Comment by curphey** [comment]
[John Viega-Exec-Bio.pdf](https://github.com/crashappsec/www-qa-issues/files/9647547/John.Viega-Exec-Bio.pdf)
[Mark-Curphey-Exec-Bio.pdf](https://github.com/crashappsec/www-qa-issues/files/9647546/Mark-Curphey-Exec-Bio.pdf)

Please find the exec bios. We can use these PDF's for now and I can add zips later.

**Comment by curphey** [comment]
Change the text to reflect PDF

**Comment by curphey** [comment]
I will close this in favour of #48 and assign that one to myself.
