### ISSUE TITLE
404 pages incomplete

### ISSUE THREAD

**Issue by nettrino** [crashappsec/www-qa-issues#22]
404 pages are not following the style of the rest of the website and contain links to dummy menu items.

<img width="1092" alt="Screenshot 2022-09-05 at 12 21 57 AM" src="https://user-images.githubusercontent.com/4614044/188334081-b93b9402-0c7f-446d-b374-7a956b5213b0.png">

**Comment by curphey** [comment]
Makes sense.

**Comment by alexdunphy** [comment]
The 404 page should match the design now: https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/404.
