### ISSUE TITLE
The general TV static animation is poor

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#24]
The overall quality of the static TV effect is poor quality. I would really like to be able to sync the style with the video animator. I can supply this when you are ready. He is very easy to work with and we can sync your his ie you take the lead.

**Comment by curphey** [comment]
Lets go with the video option assuming its performant? If so let me connect you to the video animation guy. I think Beto will need to be involved to specify the exact style and you to specify the technical reqs you need for the web. It maybe tricky connecting everyone as he was through UpWorks and I dont want to violate their "off platform" rules. If this makes sense let me work out how to connect you all.

**Comment by curphey** [comment]
Wonderful. He did send the version with the update text over the weekend. I have uploaded them to our media store here

https://drive.google.com/drive/folders/1XP5h4l3GA7QmGoNcTIUydfzBjWtxtDpg?usp=sharing

It's open to the internet. 

If you can confirm it's the latest and you are happy then please close the issues.

**Comment by alexdunphy** [comment]
@curphey The home video has been added to https://staging-www.crashoverride.com/en/?hs_preview=cgUDMhrd-53439940813 now - please give me a shout if you hit any issues with it, or if it needs replacing with one of the other videos with a different tagline.

Thanks for sending the other video links - I've downloaded the folder now, in case you want to make it private on Google Drive.
