### ISSUE TITLE
The logo has the wrong aspect ratio.

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#3]
**Sender**: mark@crashoverride.com
**Taken at**: https://crashoverride-25939634.hs-sites-eu1.com/
**Fields**:
- Add a comment: The logo has the wrong aspect ratio.

![SCREENSHOT](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/2c68dfa1-e9f4-4e72-9794-2807e62ff22a-annotated_b89f4505-76c3-47ff-b90f-1021cfba4138.png?etag=cec95f07457a34691d51d73b2e82d683)
*[Download original image](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/2c68dfa1-e9f4-4e72-9794-2807e62ff22a-annotated_b89f4505-76c3-47ff-b90f-1021cfba4138.png?etag=cec95f07457a34691d51d73b2e82d683)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 1800x1169
**Browser size**: 1591x859
**[Open #6 in Usersnap](https://app.usersnap.com/l/feedback/f93d08bc-2081-4ea1-8856-8a8a7d4664f8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by alexdunphy** [comment]
The logo aspect ratio has been updated to match the native image.

@curphey One small thing I saw - the logo downloads on the [Media](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/media) page look like they're using a slightly different version of the logo to the site (for instance the 'O' isn't joined to the 'v' in 'Override'). I'm not sure if one version is newer, but please give me a shout if you would like one version to be used everywhere.
