### ISSUE TITLE
Correct Video Tagline on Homepage 

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#38]
https://drive.google.com/file/d/1VzFfLE4OSSvo2oHe9n62eoVlAIQoukCx/view?usp=sharing

Just says "Screw Security Busy Work"

I know there we two bit rates and I think the ones marked _1 are the lowest bit rate.

**Comment by alexdunphy** [comment]
The video tagline has been updated on the [home page](https://crashoverride-25939634-hs-sites-eu1-com.sandbox.hs-sites-eu1.com/).
