### ISSUE TITLE
Images should be SVG 

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#4]
[USERSNAP] All images across the site should be using SVG's. This will 1. Avoid extra network calls, 2. be smaller, 3, only require a render() and 4. most importantly scale in a hi res browser.

**Sender**: mark@crashoverride.com
**Taken at**: https://crashoverride-25939634.hs-sites-eu1.com/
**Fields**:
- Add a comment: All images across the site should be using SVG&#39;s. This will 1. Avoid extra network calls, 2. be smaller, 3, only require a render() and 4. most importantly scale in a hi res browser.

![SCREENSHOT](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/c3a2f317-e15b-4b7f-af5d-9d8fb65c0f9c-annotated_11c888a6-3b3c-48f2-b23e-a97c4016ee6c.png?etag=5a1cbc86c4b39bb58dc77c385c7ce0f8)
*[Download original image](https://resources.usersnap.com/company/f20905be-41d6-473b-82cd-bf3f97305e10/datapoint_screenshot/c3a2f317-e15b-4b7f-af5d-9d8fb65c0f9c-annotated_11c888a6-3b3c-48f2-b23e-a97c4016ee6c.png?etag=5a1cbc86c4b39bb58dc77c385c7ce0f8)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 1800x1169
**Browser size**: 1591x859
**[Open #7 in Usersnap](https://app.usersnap.com/l/feedback/128b378f-f693-48e1-bc8c-d863c954ab64?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by alexdunphy** [comment]
I think all the images that were designed as vector have been switched over to inline SVGs now.
