### ISSUE TITLE
Unsubscribe and manage preferences pages have a giant logo

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#40]
Lets just remove the logo and go with the default HS pages for now.

**Comment by alexdunphy** [comment]
@curphey The previous developers included templates for these, which have been tweaked slightly and connected in Hubspot [here](https://app-eu1.hubspot.com/settings/25939634/marketing/email/subscriptions) now:

![mail crashoverride com_hs_manage-preferences_unsubscribe-all_languagePreference=en d=VncJJM5N6F8vVT767c4pgmrhW3T0wlb4rw4LHW3M0gX11JxwY5N1fkvKFkHJqmW6jBDND7t-Zs4W5kkdTj6sRBr1W58cvFM7jlJlLN1MSMWM723ZfW1_NMLt8fCy_KW2t0RVY85NcJTf3K2R1-04 v=3 ut](https://user-images.githubusercontent.com/1374671/192531650-414dd633-be2e-4b42-ac11-4d587bc7e0fa.png)
![mail crashoverride com_hs_manage-preferences_unsubscribe_languagePreference=en d=VncJJM5N6F8vVT767c4pgmrhW3T0wlb4rw4LHW3M0gX11JxwY5N1fkvKFkHJqmW6jBDND7t-Zs4W5kkdTj6sRBr1W58cvFM7jlJlLN1MSMWM723ZfW1_NMLt8fCy_KW2t0RVY85NcJTf3K2R1-04 v=3 utm_ca](https://user-images.githubusercontent.com/1374671/192531657-7418bc28-43c5-4284-956b-44f40b893a95.png)
