### ISSUE TITLE
match tagline across site

### ISSUE THREAD

**Issue by miki725** [crashappsec/www-qa-issues#43]
on about page:

<img width="970" alt="image" src="https://user-images.githubusercontent.com/932940/192579167-602c4394-3430-433e-ae47-825894a467ef.png">

> We are Crash Override, join our movement and f*ck appsec busy work.

I think it should be:

```
We are Crash Override, join our movement and screw security busy work.
```

**Comment by alexdunphy** [comment]
Thanks, it looks like this has been updated now.
