### ISSUE TITLE
Possible Media Page Template Issue 

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#44]
When editing the media page there appears to be some issues. I did a quick screen recording to explain as I think its easier.

**Comment by alexdunphy** [comment]
@curphey Thanks - it's safe to save the changes to the page after that happens, so feel free to go ahead and make any edits to the content there.

What's happening is that when the component gets re-rendered in the Hubspot editor (after making a change to the content), it loses its faded-in state (as some of the components on the site fade in when scrolled-to). I'm sure there'll be a fix we can add for that - perhaps disabling all animations when a page is being loaded within the Hubspot editor.

**Comment by alexdunphy** [comment]
@curphey This should be fixed now - the page elements shouldn't get hidden when editing. Please give me a shout if you're still seeing it when editing page content in Hubspot.
