### ISSUE TITLE
Properly Size Images

### ISSUE THREAD

**Issue by curphey** [crashappsec/www-qa-issues#7]
See lighthouse feedback. This will save around 3.5 - 4 seconds of page load. 
<img width="710" alt="Screenshot 2022-09-04 at 15 32 41" src="https://user-images.githubusercontent.com/143776/188318793-2616ca86-4d75-4830-b4c2-f3e3942abfd1.png">

**Comment by alexdunphy** [comment]
The images have been removed from this section now. The grid background is a CSS pattern, the TV is an inline SVG and the animation is a video.
